server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/volunteer?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wdf123456
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

jwt:
  secret: volunteer
  issuer: wb

knife4j:
  enable: true
  setting:
    enableSwaggerModels: true

mybatis-plus:
  type-aliases-package: com.graduationbackend.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true